version: '3.7'

services:

  gw-client:
    build: gw-client
    image: gw-client-img
    container_name: gw-client-con
    ports:
      - "8080:8080"
    depends_on:
      - gw-service
      - gw-frontend
#      - gw-reddis
    networks:
      - gw-network
    restart: "on-failure"

  gw-frontend:
    build: gw-ui
    image: gw-ui-img
    container_name: gw-ui-con
    ports:
      - "3000:3000"
    networks:
      - gw-network
#    restart: "on-failure"

  gw-service:
    build: gw-service
    image: gw-service-img
    container_name: gw-service-con
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://gw-db:5432/gw-data
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - gw-db
    networks:
      - gw-network
#    restart: "on-failure"

  gw-db:
    image: postgres:16.1
    container_name: gw-db-con
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=admin
      - POSTGRES_DB=gw-data
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - gw-db-data:/var/lib/postgresql/data
    networks:
      - gw-network
#    restart: "on-failure"

  gw-reddis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
#    restart: "on-failure"
    networks:
      - gw-network

volumes:
  gw-db-data:

networks:
  gw-network:
    driver: bridge
