version: '3.8'

services:
  gw-client:
    build: gw-client
    image: gw-client-img
    depends_on:
      - consul
    networks:
      - gw-overlay
      - gw-internal
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

  gw-service:
    build: ./gw-service
    env_file:
      - ./gw-service/.env
    image: gw-service-img
    depends_on:
      - gw-db
      - gw-redis
      - gw-client
    networks:
      - gw-internal
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.type == backend

  gw-db:
    image: postgres:16.1
    container_name: gw-db-con
    env_file:
      - ./gw-db/.env
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - gw-db-data:/var/lib/postgresql/data
    networks:
      - gw-internal
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.type == backend

  gw-redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - gw-internal
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.type == backend

  consul:
    image: consul:1.14.0
    container_name: consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - gw-internal
    restart: always
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.type == backend

volumes:
  gw-db-data:

networks:
  gw-internal:
    driver: bridge
  gw-overlay:
    driver: overlay
    attachable: true
