server.port=9090
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always

logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.redis.host=gw-redis
spring.redis.port=6379
spring.redis.database=0
spring.redis.timeout=60000
spring.redis.lettuce.pool.max-active=8
spring.redis.lettuce.pool.max-idle=8
spring.redis.lettuce.pool.min-idle=0
spring.redis.lettuce.pool.max-wait=-1
spring.redis.lettuce.shutdown-timeout=100ms
spring.redis.lettuce.pool.time-between-eviction-runs=60000

spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.username=arinmun@yandex.ru
spring.mail.password=***
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret = jl1929MyfUeRgmRVHx07Qg/nicNEeRf5JJJF+s46mcA=

spring.liquibase.change-log=classpath:db.changelog-master.yaml

spring.application.name=gw-service
spring.cloud.consul.host=consul
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.service-name=gw-service
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.health-check-timeout=3s

spring.cloud.consul.discovery.instance-id=gw-service-${HOSTNAME}


spring.cloud.loadbalancer.cache.enabled=true
spring.cloud.loadbalancer.cache.caffeine.spec=maximumSize=500,expireAfterWrite=5s

spring.cache.type=caffeine
spring.cache.cache-names=defaultCache
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=30m
