server.port=8080


management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true


management.endpoint.health.group.liveness.include=livenessState
management.endpoint.health.group.readiness.include=readinessState
management.endpoint.health.group.system.include=diskSpace,ping


spring.application.name=gw-client
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true




gw-service.url=http://gw-service:9090

server.tomcat.max-threads=200
server.tomcat.min-spare-threads=20
server.tomcat.connection-timeout=5000