server.port=8080
spring.application.name=gw-client
spring.cloud.consul.discovery.instance-id=gw-client-${HOSTNAME}
spring.cloud.consul.discovery.service-name=gw-client
spring.cloud.consul.host=consul
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.health-check-timeout=3s